database.driverClassName=com.mysql.jdbc.Driver
database.url=jdbc:mysql://maildb-1.jwmhosting.com/mail3x?autoReconnect=true
database.username=JWMBOS
database.password=12040Linc

vendorAdapter.database=MYSQL

openjpa.streaming=false
